// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx8Tpq7V7jSs2m5kIryN3mxdCT7hBGQh4',
    appId: '1:243913496121:web:519dcc7b789308054e5fe8',
    messagingSenderId: '243913496121',
    projectId: 'real-estate-map-fb636',
    authDomain: 'real-estate-map-fb636.firebaseapp.com',
    storageBucket: 'real-estate-map-fb636.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyROQh1r8WqaFyu00yJCIWcbEfTpmTaZ8',
    appId: '1:243913496121:android:900447d46ae13d984e5fe8',
    messagingSenderId: '243913496121',
    projectId: 'real-estate-map-fb636',
    storageBucket: 'real-estate-map-fb636.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4F9PU_oYOTm8EJZvQsSDwr-Nd_6I-5Wg',
    appId: '1:243913496121:ios:10b42c2933bdbada4e5fe8',
    messagingSenderId: '243913496121',
    projectId: 'real-estate-map-fb636',
    storageBucket: 'real-estate-map-fb636.firebasestorage.app',
    iosBundleId: 'com.example.realEstateMapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4F9PU_oYOTm8EJZvQsSDwr-Nd_6I-5Wg',
    appId: '1:243913496121:ios:10b42c2933bdbada4e5fe8',
    messagingSenderId: '243913496121',
    projectId: 'real-estate-map-fb636',
    storageBucket: 'real-estate-map-fb636.firebasestorage.app',
    iosBundleId: 'com.example.realEstateMapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx8Tpq7V7jSs2m5kIryN3mxdCT7hBGQh4',
    appId: '1:243913496121:web:ad0c54e97b37df4f4e5fe8',
    messagingSenderId: '243913496121',
    projectId: 'real-estate-map-fb636',
    authDomain: 'real-estate-map-fb636.firebaseapp.com',
    storageBucket: 'real-estate-map-fb636.firebasestorage.app',
  );
}
