name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 1. 내 코드 가져오기
      uses: actions/checkout@v4
      
    - name: 2. 자바(Java) 세팅
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: 3. 플러터(Flutter) 세팅
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
        
    - name: 4. 숨겨둔 .env 파일 복구하기 (핵심!)
      env:
        ENV_CONTENT: ${{ secrets.ENV_FILE }}
      run: echo "$ENV_CONTENT" > .env
        
    - name: 5. 패키지 다운로드
      run: flutter pub get
      
    - name: 6. 안드로이드 APK 빌드
      run: flutter build apk --release
      
    - name: 7. 완성된 APK 파일 다운로드 링크 만들기
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: build/app/outputs/flutter-apk/app-release.apk